### ISSUE TITLE
about footer's background color

### ISSUE THREAD

**Issue by TCPsoftware** [AmazingApps/AmazingApps.github.io#14]
Could you change a background color for <a href="http://amazingapps.org/index.html#three">get in touch</a> and <a href="http://amazingapps.org/index.html#footer">footer</a>?
Maybe it looks ugly and not intuitive now.

**Comment by Riajyuu** [comment]
Em
That's interesting.
What color do you suggest since I think it looks more universal in designing language now.

**Comment by TCPsoftware** [comment]
Maybe a deep color ?
or a background image will also be suitable.
Then the module will be more intuitive.

**Comment by TCPsoftware** [comment]
and more probably to let others get in touch with your organization

**Comment by Riajyuu** [comment]
That's interesting.
You may join our telegram group for further discussion via the given invitation links.
That's for your time.

**Comment by TCPsoftware** [comment]
sorry but i could not launch telegram because of China's Great Firewall

**Comment by gloomy-ghost** [comment]
It's just a form of minimalism design, closing as intended behaviour.
