### ISSUE TITLE
en-us version of homepage

### ISSUE THREAD

**Issue by Riajyuu** [AmazingApps/AmazingApps.github.io#4]
use the top-right area to place buttons to swtich languages

**Comment by gloomy-ghost** [comment]
Where are we putting the English pages? Something like en.amazingapps.org or amazingapps.org/en/?

**Comment by Riajyuu** [comment]
个人建议如下：

1. 分离页面文本
2. 默认主页为英文
3. 右上角可切换语言的按钮
4. 使用amazingapps.org/zh-CN/
